---
title: "Volcanic Activity"
author: "Aaron Schlafly"
date: "2/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(leaflet)
library(htmltools)
```


The data come from the US Geologic Service (USGS) at https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_month.csv.
It is updated every minute, so I output the time at which the data was read in. 
It only includes earthquakes with magnitude greater than 2.5.  

``` {r read_data, comment = ""}
qdb = read.csv(url("https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_month.csv"))
quakes = qdb %>% select(c("latitude","longitude",mag))
Sys.time()
```

``` {r show_data}
quakes %>% 
  leaflet() %>% 
  addTiles() %>% 
  addCircleMarkers(lng = quakes$longitude, 
                   lat = quakes$latitude, 
                   radius = sqrt(exp(quakes$mag))/2,
                   popup = ~htmlEscape(quakes$mag),
                   color = "red",
                   stroke = FALSE, 
                   fillOpacity = 0.3)
```


